version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    container_name: jimin-blog-dev
    stdin_open: true
    env_file:
      - ./.env.local
